### ISSUE TITLE
Fix Cairo font backend for browser

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/r3dfox-old#137]
Currently it looks like this with Cairo enabled

![rkj8rw](https://github.com/user-attachments/assets/78ec8d92-7273-43c1-a7b8-ba224e2007c9)

**Comment by the-r3dacted** [comment]
More info on the issue, a related issue first occurred in Firefox 89 when trying to use it on the Vista extended kernel, looking into it, it seems to be caused by the GDI only fallback for the rendering engine applying on all systems pre-7 RTM or build 7600. r3dfox lowers this to 6000 I think or makes it work on Vista+ so the issue doesn't occur.

Cairo also runs into this issue, and the source of it is this.

https://bugzilla.mozilla.org/show_bug.cgi?id=1698495

However unless someone helps me build Firefox 89/91 in modern times, I'm probably never going to be able to figure this out. What would be best I'd think is keeping size-adjust and fixing the issue or at least disabling it in these cases, but if it needs to be ripped out that's fine too. This entire size-adjust shit seems kinda dumb.

**Comment by e3kskoy7wqk** [comment]
The cause of the issue might be simpler than expected. I suspect it's caused by an oversight Mozilla made in https://github.com/mozilla/gecko-dev/commit/39edce2d718c46b3a94c5ee62510249f6a148755

In gfx/thebes/gfxFont.cpp, the initial value of `mAdjustedSize` was changed from 0.0 to -1.0:

```diff
diff --git a/gfx/thebes/gfxFont.cpp b/gfx/thebes/gfxFont.cpp
index 8e1ab2e886a2..4a651f66437d 100644
--- a/gfx/thebes/gfxFont.cpp
+++ b/gfx/thebes/gfxFont.cpp
@@ -796,7 +796,7 @@ gfxFont::gfxFont(const RefPtr<UnscaledFont>& aUnscaledFont,
     : mFontEntry(aFontEntry),
       mUnscaledFont(aUnscaledFont),
       mStyle(*aFontStyle),
-      mAdjustedSize(0.0),
+      mAdjustedSize(-1.0),  // negative to indicate "not yet initialized"
       mFUnitsConvFactor(-1.0f),  // negative to indicate "not yet initialized"
       mAntialiasOption(anAAOption),
       mIsValid(true),
```

However, in gfx/thebes/gfxGDIFont.cpp's gfxGDIFont::Initialize(), I noticed:
```cpp
void gfxGDIFont::Initialize() {
  NS_ASSERTION(!mMetrics, "re-creating metrics? this will leak");

  LOGFONTW logFont;

  if (mAdjustedSize == 0.0) {
    mAdjustedSize = GetAdjustedSize();
    ......
```

Since `mAdjustedSize` now starts as -1.0, the initialization code in gfxGDIFont never gets executed.

Changing the condition from `if (mAdjustedSize == 0.0)` to `if (mAdjustedSize < 0.0)` should fix the issue. I believe Mozilla forgot to update this check when they modified the initial value.

**Comment by e3kskoy7wqk** [comment]
Another strange thing is that Firefox for windows 7 fails to launch on Windows 7 build 7100. I tested both Firefox 115 and Firefox 110, and neither could launch on Windows 7 build 7100 either. However, I noticed that [r3dfox v136.0.4](https://github.com/Eclipse-Community/r3dfox/releases/tag/v136.0.4%2BeRust-1.85.1) can successfully launch on Windows 7 build 7100. I'm curious to know what modifications you made to enable r3dfox to work on Windows 7 build 7100.

**Comment by the-r3dacted** [comment]
> Changing the condition from `if (mAdjustedSize == 0.0)` to `if (mAdjustedSize < 0.0)` should fix the issue. I believe Mozilla forgot to update this check when they modified the initial value.

I decided to change it to <= 0.0, and that fixed the issue. Now both Skia GDI and Cario seemingly work fine now. Thank you for helping me figure out the fix to this issue. I probably never would've figured this out on my own.

I had deleted my 7100 VM because I didn't want to deal with the timebomb, so I made a new VM with a debombed 7000 I had lying around, and r3dfox doesn't run on 7000. So I installed 7100 and checked, and r3dfox is able to open and show fonts just fine. Although it still crashes so I guess the crashing issue might not be the old DirectWrite, and maybe the DirectWrite issue was fixed at some point idk.

Cairo causes Vista SP2 6003, 7 RC 7100, and 7 RTM 7600 to crash at launch. So I may need to downgrade it or workaround whatever missing function(s) there may be that causes it to crash. (This will be trial and error for me. I don't know how to use a debugger.) Before I decide to downgrade it though, I'll try maining Cairo to see if it works well as the azure backend.

Next what I want to focus on now is that modern Firefox seems to just ignore the system ClearType settings. I'll need to trace this.

![Image](https://github.com/user-attachments/assets/8f00af22-6337-4ac7-8ffa-0ba27ecb007b)

> Another strange thing is that Firefox for windows 7 fails to launch on Windows 7 build 7100. I tested both Firefox 115 and Firefox 110, and neither could launch on Windows 7 build 7100 either. However, I noticed that [r3dfox v136.0.4](https://github.com/Eclipse-Community/r3dfox/releases/tag/v136.0.4%2BeRust-1.85.1) can successfully launch on Windows 7 build 7100. I'm curious to know what modifications you made to enable r3dfox to work on Windows 7 build 7100.

I didn't do anything in particular for 7100. I assume one of the Vista support changes I made fixed 7100 (somewhat)

**Comment by the-r3dacted** [comment]
Ok it looks like I am downgrading Cairo. It is kinda broken.

**Comment by the-r3dacted** [comment]
Actually idk. I tried my 130 with downgraded Cairo and it seems about the same. 130 with old Cairo still crashes on old Windows versions, and it doesn't work without e10s still. (Although old Cairo crashes the tabs instead of crashing the whole browser at least)

**Comment by e3kskoy7wqk** [comment]
> Another strange thing is that Firefox for windows 7 fails to launch on Windows 7 build 7100. I tested both Firefox 115 and Firefox 110, and neither could launch on Windows 7 build 7100 either.

Most likely caused by https://github.com/mozilla/gecko-dev/commit/0fd7a7ea1af6763f286e793d1ca3fa99680b5bfd, it appears some deadlock is occurring.

![Image](https://github.com/user-attachments/assets/b842f314-80d0-48b7-aa69-644b6908219e)

**Comment by the-r3dacted** [comment]
I wonder, what happens if you run this on 7100

https://github.com/Eclipse-Community/r3dfox/releases/tag/v115.13.0esr

**Comment by e3kskoy7wqk** [comment]
It starts up successfully, but the text cannot be displayed properly.

![Image](https://github.com/user-attachments/assets/6bbdb37a-902f-49a4-b4c4-9219929f18dc)

**Comment by the-r3dacted** [comment]
I wonder if SRW locks are a bit broken in 7100. Because I noticed a lot of usage of mLock, and for Vista I reverted to Critical Sections for a lot of of the C code.

That could explain r3dfox 115 running here while official 115 doesn't.

**Comment by e3kskoy7wqk** [comment]
I'm not certain, because I am seeing similar behavior on a Vista SP2 without any updates: Firefox for windows 7 fails to launch while r3dfox starts successfully.

You can test it yourself: 
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/releases/download/old/firefox-141.0a1.en-US.win32.zip
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/releases/download/old/api-ms-win-core-winrt-error-l1-1-0.dll

**Comment by the-r3dacted** [comment]
> I'm not certain, because I am seeing similar behavior on a Vista SP2 without any updates: Firefox for windows 7 fails to launch while r3dfox starts successfully.

r3dfox doesn't launch on a Vista SP2 without any updates though?

**Comment by e3kskoy7wqk** [comment]
r3dfox launchs successfully on a Vista SP2 without any updates

**Comment by the-r3dacted** [comment]
![Image](https://github.com/user-attachments/assets/ecbcd87b-91af-432a-9676-c9b4e8dc7cdd)

![wat](https://cdn.discordapp.com/emojis/1374551705756368956.gif?size=48)

**Comment by the-r3dacted** [comment]
r3dfox on Vista for me needs at least the platform update for DWrite so it can run.

![Image](https://github.com/user-attachments/assets/d3e5514b-db8f-4455-a8d4-fc30d78bd7a7)

If r3dfox runs on your end, you must have at least the platform update or some sort of workaround for DWrite.

**Comment by the-r3dacted** [comment]
Your 139 and 140 seem to run fine in my VM, so I can only assume there's some breaking change in 141. Luckily it's so early maybe it's not too much of a hassle to bisect for it.

**Comment by e3kskoy7wqk** [comment]
> r3dfox on Vista for me needs at least the platform update for DWrite so it can run.

Well... I must have remembered it wrong.
